<footer>
	<h2>Creators</h2>
		<p>Kaleb Chitaphong: Information Architect</p>
		<p>Reeshad Rahman: Designer</p>
		<p>Sharfuz Shifat: Coder</p>
	<h2>Original Student Websites</h2>
		<p><a href="http://www.csc174.org/assignment02/bsmart/">Brandon's Original Site</a></p>
		<p><a href="http://www.csc174.org/assignment02/fclark2/">Famous' Original Site</a></p>
		<p><a href="http://www.csc174.org/assignment02/kchitap/">Kaleb's Original Site</a></p>
</footer>